# Generated by Django 4.2.6 on 2023-10-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionmodel',
            name='suggestion',
            field=models.TextField(max_length=255),
        ),
    ]
