# Generated by Django 4.2.6 on 2023-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_suggestionmodel_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubHouseBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=255)),
                ('from_date', models.DateField(max_length=30)),
                ('to_date', models.DateField(max_length=30)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
