# Generated by Django 4.2.6 on 2023-10-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_memberprofilemodel_profile'),
        ('main', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubHouseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=255)),
                ('from_date', models.DateField(max_length=30)),
                ('to_date', models.DateField(max_length=30)),
                ('content', models.TextField()),
                ('total_days', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.membersmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='clubHouseBookingModel',
        ),
    ]
