# Generated by Django 4.2.6 on 2023-10-27 06:43

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clubhousebooking_delete_clubhousebookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergencyContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.FileField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
