# Generated by Django 4.2.6 on 2023-10-27 20:38

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_emergencycontactsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
