# Generated by Django 4.2.6 on 2023-10-27 21:30

import authentication.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_img', models.ImageField(default='default-profile.png', upload_to=authentication.helpers.custom_file_name)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
