# Generated by Django 4.2.6 on 2023-10-31 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_membersmodel_otp'),
        ('main', '0008_gallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='suggestion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.membersmodel'),
            preserve_default=False,
        ),
    ]
