# Generated by Django 4.2.6 on 2023-11-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_suggestionmodel_suggestion_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='suggestionModel',
        ),
    ]
